--- name:default
point_cloud_height: 144
point_cloud_width: 174

# Configuration parameters for the ICP.
gicp_config:
  max_correspondence_distance: 0.5
  maximum_iterations: 50
  transformation_epsilon: 1.0
  euclidean_fitness_epsilon: 1.0
  correspondence_randomness: 20
  maximum_optimizer_iterations: 20
  rotation_epsilon: 1.0
  point_cloud_density: 0.2
  max_fitness_score: 1.0
  position_sigma: 0.01
  orientation_sigma: 0.001
  max_sensor_distance: 2.0

# Configuration parameters for the bilateral filter.
bfilter_config:
  spatial_width: 15.0
  range_sigma: 0.05

# Set to true if output debug information is desirable.
output_debug: true
# Time in s between point_cloud_source readings
point_cloud_source_period: 0.1
# Time in s between point_cloud_target readings
point_cloud_target_period: 0.1
# list of static transformations
static_transformations: []
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.2
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
